# Generated by Django 3.1.2 on 2021-05-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20210516_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='avatar',
        ),
    ]
